plamo/01_minimum/network.txz/curl/PlamoBuild.curl-7.40.0
plamo/01_minimum/network.txz/curl/patch-lib_curl__sasl__gssapi.c

* arch は uname -m で決定
* curl_sasl_gssapi.c でのコンパイルエラーに対応するパッチを適用

plamo/01_minimum/curl: 7.40.0 への更新

---

plamo/04_xapps/firefox/PlamoBuild.firefox-35.0

* 32.0 以降 32bit 版で無効にしていた最適化を復活

plamo/04_xapps/firefox: 35.0 への更新

---

plamo/01_minimum/gnupg_tls.txz/libtasn1/CVE-2014-3467.patch
plamo/01_minimum/gnupg_tls.txz/libtasn1/CVE-2014-3468.patch
plamo/01_minimum/gnupg_tls.txz/libtasn1/CVE-2014-3469.patch
plamo/01_minimum/gnupg_tls.txz/libtasn1/CVE-2015-2806.patch
plamo/01_minimum/gnupg_tls.txz/libtasn1/PlamoBuild.libtasn1-2.14

* CVE-2014-3467
* CVE-2014-3468
* CVE-2014-3469
* CVE-2015-2806
* 署名確認
* arch検出

plamo/01_minimum/gnupg_tls.txz/libtasn1: 2.14への更新と脆弱性対応

---

plamo/05_ext/network2.txz/php/PlamoBuild.php-5.6.11

* configure オプションに --with-libzip を追加
* この設定でパッケージをリリースするのは次のバージョンとする

plamo/05_ext/network2.txz/php: システムのlibzipを使用するようにした

---

plamo/01_minimum/libxml2/CVE-2015-1819.patch
plamo/01_minimum/libxml2/PlamoBuild.libxml2-2.9.2
plamo/01_minimum/libxml2/xmlcaltalog-bugfix.patch

* Buildスクリプト中でsedで行った修正をパッチとして外だし
(libxml2 で修正されているため、次バージョンでは不要のため)

plamo/01_minimum/libxml2: CVE-2015-1819 対応

---

plamo/05_ext/mariadb/PlamoBuild.mariadb-10.1.9

DOCS ファイルの調整．/ に不要なリンクを張っていたのを削除．
配布してないけど，mariadb_testsuites のファイル名を変更．
ついでに新しいバージョンが出ていたので mariadb 10.1.9 に更新．

mariadb 10.1.9 に更新．

---

plamo/01_minimum/network.txz/bind/PlamoBuild.bind-9.9.8

plamo/01_minimum/network.txz/bind: 9.9.8 への更新

---

plamo/00_base/iproute2/PlamoBuild.iproute2-4.2.0

64bit 版は tc 関連のモジュールを /usr/lib64/tc にインストールするように変更

plamo/00_base/iproute2: 4.2.0 への更新

---

plamo/05_ext/gnome_parts.txz/totem_pl_parser/PlamoBuild.totem-pl-parser-3.10.6
plamo/05_ext/gnome_parts.txz/totem_pl_parser/totem-disc_h.patch

古いソフトが totem-disc.h を include している場合があるので追加でイン
ストールするようにした

plamo/05_ext/gnome_parts.txz/totem_pl_parser: 追加でヘッダをインストール

---

plamo/01_minimum/network.txz/ntp/PlamoBuild.ntp-4.2.8p7

archive.ntp.org にアクセスできないのでダウンロード元も変更

plamo/01_minimum/network.txz/ntp: 4.2.8p7 への更新

---

plamo/04_xapps/thunderbird/PlamoBuild.thunderbird-45.1.0

gtk2 ですでにリリースしたので改めてリリースしない。次に向けて。

plamo/04_xapps/thunderbird: gtk3 を使うように変更

---

plamo/01_minimum/network.txz/curl/PlamoBuild.curl-7.49.1

--without-nghttp2 を付与 (05_ext 以下なので)

plamo/01_minimum/network.txz/curl: 7.49.1 への更新

---

plamo/05_ext/libarchive/PlamoBuild.libarchive-3.2.1

互換ライブラリを参照しているバイナリはなさそうなので削除した。

plamo/05_ext/libarchive: 3.2.1 への更新

---

plamo/00_base/sysvinit/etc/rc.d/rc.6

NFSマウントされていた場合にumountするコードがあるが、mount -vの出力の有無を見ており、今のmountコマンドだとNFSマウントの有無に関わらず状態表示がされるため、NFSマウントされていなくてもumountが実行されるため

[RFC] plamo/00_base/sysvinit: rc.6スクリプトの更新

---

admin/make_PlamoBuild.py
admin/plamobuild_functions.sh

* 一部、複数ソースを処理するコードが残っていたので除去
* ソースが git の場合の対応
* ソースアーカイブの展開時、圧縮形式は tar コマンドに任せるようにした
* ソースアーカイブが *.zip なら unzip コマンドで展開するようにした
* arch によってビルドディレクトリを分ける処理を廃止
* (なるべく処理をわかりやすくするようにしています)
* build out of tree の場合、autogen.sh をソースディレクトリで実行するように修正

複数ソース処理、不要な処理の除去と git 対応

---

admin/make_PlamoBuild.py

ソースディレクトリをビルド用にコピーする際、ソースディレクトリ以下のファ
イルを "*" でコピーしていたのを、ディレクトリごとコピーするようにした

admin/make_PlamoBuild.py: ソースツリーのコピー方法の変更

---

admin/plamobuild_functions.sh

/usr/share 以下にディレクトリ以外の "locale" があった場合、make
install したファイルを消去してしまう可能性がある

admin/plamobuild_functions.sh: locale 以下の処理の不具合修正

---

admin/plamobuild_functions.sh

admin/plamobuild_functions.sh: 修正ミスの修正

---

plamo/01_minimum/network.txz/ntp/PlamoBuild.ntp-4.2.8p9
plamo/01_minimum/network.txz/ntp/ntp.conf
plamo/01_minimum/network.txz/ntp/ntp.init

* ntpd は ntp ユーザ・グループで起動するようにした
* ntp.conf の設定を今風（セキュア）にした。デフォルトでは localhost からしか受け付けない
* ドリフトファイルの場所を /var/lib/ntp へ（ntp:ntp 所有)

plamo/01_minimum/network.txz/ntp: 4.2.8p9-P2 に更新

---

admin/make_PlamoBuild.py
admin/plamobuild_functions.sh

* "$verify"でハッシュ・署名ファイルのURLを指定できるようにした
* ハッシュ/署名ファイルの存在URLが明らかであるなら、指定したほうがwgetのspiderモードを使うよりダウンロード元のリソースを消費しない
* spiderモードは302でリダイレクトされる場合もエラーになるので存在しているファイルもエラーになり、ダウンロード元に余計な負荷をかける
* "$verify"が未定義or空文字列であれば今までどおりspiderモードを使う

admin: ソース確認用のハッシュ/署名ファイルのURLを指定できるようにした

---

contrib/Network/google_chrome/PlamoBuild.google-chrome-60.0.3112.78

contrib/Network/google_chrome: 60.0.311.7 への更新

---

plamo/02_devel/git/PlamoBuild.git-2.17.0

* --with-libpcre2 削除
* --with-libpcre1 は Plamo の pcre が要件を満たさないようなのでいったん PCRE サポートを削除

git 2.17.0 B2

---

plamo/00_base/shadow/PlamoBuild.shadow-4.5
plamo/00_base/shadow/adduser
plamo/00_base/shadow/chage.pam
plamo/00_base/shadow/login.pam
plamo/00_base/shadow/passwd.pam
plamo/00_base/shadow/su.pam

* adduser
- 非日本語モードのときにIMでfcitxが選択できないバグを修正
- 非日本語モードのときはLANG=ja_JP.*の場合でもLANG=Cでコマンドを実行するようにした
* plamo-7.x branchの作成時に抜けていたファイル（pam関連）を追加

plamo/00_base/shadow: 4.5 B8
