- contrib/Network/wireshark/PlamoBuild.wireshark-1.10.12
> contrib/Network/wireshark: 1.10.12 への更新

- contrib/Network/rdesktop/PlamoBuild.rdesktop-1.7.0
> contrib/Network/rdesktop: スクリプト微調整

- plamo/07_kde/qtruby/PlamoBuild.qtruby-4.14.3
- plamo/07_kde/redland_bindings/PlamoBuild.redland-bindings-1.0.17.1
> redland_bindings, qtruby

- plamo/05_ext/network2.txz/remctl/PlamoBuild.remctl-3.2
* ruby 2.2 対応のため
* url に変数導入
* arch 自動設定
> plamo/05_ext/network2.txz/remctl: P2 -> P3 更新

- plamo/01_minimum/libzip/CVE-2015-2331.patch
- plamo/01_minimum/libzip/PlamoBuild.libzip-0.11.2
> plamo/01_minimum/libzip: 0.11.2に更新

- plamo/00_base/openssh/PlamoBuild.openssh-7.0p1
* --with-md5-password の追加
* ssh-copy-id コマンドの追加
> plamo/00_base/openssh: 7.0p1 への更新

- admin/get_depends.py
- admin/query_depends.py
最近の Plamo での動作確認してないですけど，見つけにくいのでコピーしてみました．
> こじまさん作成のツールを web の方からコピー．

- plamo/00_base/hdsetup/files/sbin/installpkg2
> こじまさんがメールに流していた diff を登録．

- plamo/06_xfce/garcon/PlamoBuild.garcon-0.5.0
> plamo/06_xfce/garcon: 0.5.0 への更新

- plamo/01_minimum/autofs/PlamoBuild.autofs-5.1.1
* パッチの削除
* init スクリプトの stop 時に sleep 1 を入れるパッチを添付
- stop 時に 20 秒待ってしまうのを防ぐため
* verify 追加
> plamo/01_minimum/autofs: 5.1.1 への更新

- contrib/Utilities/aufs-util/PlamoBuild.aufs-util-4.0
> contrib/Utilities/aufs-util: 追加

- contrib/Network/google_chrome/PlamoBuild.google-chrome-50.0.2661.75
chrome 50 になって Linux 版が軽くなったと聞いて :-)
> contrib/Network/google_chrome: 50.0.2661.75 への更新

- plamo/02_x11/expat/CVE-2016-0718-v2-2-1.patch
- plamo/02_x11/expat/PlamoBuild.expat-2.1.1
> plamo/02_x11/expat: 2.1.1 への更新と CVE-2016-0718 パッチ適用

- plamo/05_ext/network2.txz/httpd/PlamoBuild.httpd-2.4.20
> plamo/05_ext/network2.txz/httpd: 2.4.20 への更新

- admin/make_PlamoBuild.py
- admin/make_PlamoBuild_allin.py
- admin/plamobuild_functions.sh
* 従来のmake_PlamoBuildを_allinと付けてリネーム
* 生成したビルドスクリプトが使う共通関数用plamobuild_functions.shを追加
> 新しいmake_PlamoBuild.pyの追加

- plamo/04_xapps/firefox/PlamoBuild.firefox-48.0
- plamo/04_xapps/firefox/mozilla-1282843.patch
* スクリプトの不要な部分を除去
* configure オプションで--libdirが指定できなくなっていたのでパッチ追加
* LANG=C でビルドがうまくいく感じなので指定
* 日本語リソースの取得元を変更
> plamo/04_xapps/firefox: 48.0 への更新

- admin/plamobuild_functions.sh
* rm -f $infodir/dir
* untabify
* remove some trailing white spaces
> Add proc for removing dir file

- plamo/01_minimum/devel.txz/gettext/PlamoBuild.gettext-0.19.7
* emacs or emacs_mini を検出し、存在する場合は po-mode.el, elc をインストール
> plamo/01_minimum/devel.txz/gettext: P3 への更新

- admin/plamobuild_functions.sh
> plamobuild_functions: Compress info files if exists

- plamo/00_base/sysvinit/PlamoBuild.sysvinit-2.88dsf
- plamo/00_base/sysvinit/etc/rc.d/rc.6
複数のNFSマウントがある場合に複数回umountが実行される問題を修正
> plamo/00_base/sysvinit: rc.6でNFSマウントを検出するロジックの変更

- plamo/04_xapps/firefox/PlamoBuild.firefox-50.0.2
> plamo/04_xapps/firefox: 50.0.2 への更新

- plamo/01_minimum/network.txz/curl/PlamoBuild.curl-7.54.0
--enable-threaded-resolver を指定してみた
> plamo/01_minimum/network.txz/curl: 7.54.0 への更新

- contrib/Network/google_chrome/PlamoBuild.google-chrome-61.0.3163.79
- contrib/Virtualization/lxc/PlamoBuild.lxc-2.1.0
- contrib/Virtualization/lxc/after-2.1.0.patch
This reverts commit e794e17bd439af419372c0bb651d0c0f80d2a014.
> Revert "Revert "contrib/Network/google_chrome: 61.0.3163.79 への更新""

- contrib/Virtualization/lxc/PlamoBuild.lxc-2.1.0
shutdown スクリプト内のコンテナには不要な処理を削除
> contrib/Virtualization/lxc: lxc-plamo に対するパッチ適用

- contrib/Network/google_chrome/PlamoBuild.google-chrome-62.0.3202.62
- plamo/00_base/openssh/PlamoBuild.openssh-7.6p1
- plamo/01_minimum/network.txz/bind/PlamoBuild.bind-9.9.11
* bind 9.9.11
* chrome 62.0.3202.62 (only update script)
> bind and chrome

- contrib/Network/google_chrome/PlamoBuild.google-chrome-63.0.3239.84
> contrib/Network/google_chrome: 63.0.3239.84 への更新

- plamo/00_base/openssl/PlamoBuild.openssl-1.1.0h
- plamo/00_base/openssl/c_rehash.patch
Fix the problem of /usr/bin/c_rehash script. Add a patch.
> plamo/00_base/openssl: 1.1.0h B2

- plamo/01_minimum/ca_certificate/PlamoBuild.ca_certificate-0.7_20180509
* make_ca スクリプトを github の make-ca-0.7 に変更
* cacert の class 3 CA の証明書もインストールするように変更
> plamo/01_minimum/ca_certificate: 0.7_20180509

- plamo/07_multimedia/ffmpeg/PlamoBuild.ffmpeg-3.4.2
> plamo/07_multimedia/ffmpeg: 3.4.2 B2

- plamo/07_multimedia/mplayer/PlamoBuild.mplayer-export-2018-05-13
- plamo/07_multimedia/mplayer/PlamoBuild.mplayer-export-2018-05-14
- plamo/07_multimedia/mplayer/mplayer.desktop
* applications ファイルの追加
* /etc/mplayer にソース付属の conf ファイルをコピー
> plamo/07_multimedia/mplayer: 2018-05-14

- plamo/00_base/shadow/PlamoBuild.shadow-4.5
- plamo/00_base/shadow/adduser
* adduserコマンドでfcitxを選択した際のバグ修正
> plamo/00_base/shadow: 4.5 B9

- plamo/08_daemons/php/PlamoBuild.php-7.2.8
> plamo/08_daemons/php: 7.2.8 B2

- plamo/08_daemons/nsd/PlamoBuild.nsd-4.1.23
- plamo/08_daemons/nsd/nsd.init
- plamo/08_daemons/unbound/PlamoBuild.unbound-1.7.1
> nsd-4.1.23, unbound-1.7.1
